### ISSUE TITLE
build error using premake4_linux64

### ISSUE THREAD

**Issue by consultit** [bulletphysics/bullet3#1538]
Hi I'm trying to build bullet on GNU/Linux (debian 9.3) using these commands
```
$ ./premake4_linux64 --enable_pybullet gmake
$ cd gmake/
$ make all
```
but I get these errors:
```
...
==== Building App_PhysicsServer_SharedMemory (release64) ====
Linking App_PhysicsServer_SharedMemory
obj/x64/Release/App_PhysicsServer_SharedMemory/b3PluginManager.o: In function `b3PluginManager::loadPlugin(char const*, char const*)':
b3PluginManager.cpp:(.text+0x1060): undefined reference to `dlopen'
b3PluginManager.cpp:(.text+0x14cb): undefined reference to `dlsym'
b3PluginManager.cpp:(.text+0x14df): undefined reference to `dlsym'
b3PluginManager.cpp:(.text+0x14f3): undefined reference to `dlsym'
b3PluginManager.cpp:(.text+0x1507): undefined reference to `dlsym'
b3PluginManager.cpp:(.text+0x151b): undefined reference to `dlsym'
obj/x64/Release/App_PhysicsServer_SharedMemory/b3PluginManager.o:b3PluginManager.cpp:(.text+0x152f): more undefined references to `dlsym' follow
obj/x64/Release/App_PhysicsServer_SharedMemory/b3PluginManager.o: In function `b3PluginManager::loadPlugin(char const*, char const*)':
b3PluginManager.cpp:(.text+0x15d2): undefined reference to `dlclose'
b3PluginManager.cpp:(.text+0x1728): undefined reference to `dlclose'
b3PluginManager.cpp:(.text+0x1c80): undefined reference to `dlclose'
obj/x64/Release/App_PhysicsServer_SharedMemory/b3PluginManager.o: In function `b3PluginManager::unloadPlugin(int)':
b3PluginManager.cpp:(.text+0x2a24): undefined reference to `dlclose'
obj/x64/Release/App_PhysicsServer_SharedMemory/b3PluginManager.o: In function `b3PluginManager::registerStaticLinkedPlugin(char const*, int (*)(b3PluginContext*), void (*)(b3PluginContext*), int (*)(b3PluginContext*, b3PluginArguments const*), int (*)(b3PluginContext*), int (*)(b3PluginContext*), UrdfRenderingInterface* (*)(b3PluginContext*))':
b3PluginManager.cpp:(.text+0x3539): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
App_PhysicsServer_SharedMemory.make:152: recipe for target '../../bin/App_PhysicsServer_SharedMemory_gmake_x64_release' failed
make[1]: *** [../../bin/App_PhysicsServer_SharedMemory_gmake_x64_release] Error 1
Makefile:40: recipe for target 'App_PhysicsServer_SharedMemory' failed
make: *** [App_PhysicsServer_SharedMemory] Error 2
```

**Comment by EastskyKang** [comment]
same here. 

I am using cmake 3.5 

 ```
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBody.o): In function `btSoftBody::updatePose() [clone .part.103] [clone .constprop.409]':
btSoftBody.cpp:(.text+0x1c77): undefined reference to `btPolarDecomposition::decompose(btMatrix3x3 const&, btMatrix3x3&, btMatrix3x3&) const'
btSoftBody.cpp:(.text+0x2003): undefined reference to `btPolarDecomposition::btPolarDecomposition(float, unsigned int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBody.o): In function `btSoftBody::updateClusters()':
btSoftBody.cpp:(.text+0xc154): undefined reference to `btPolarDecomposition::decompose(btMatrix3x3 const&, btMatrix3x3&, btMatrix3x3&) const'
btSoftBody.cpp:(.text+0xcc33): undefined reference to `btPolarDecomposition::btPolarDecomposition(float, unsigned int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o): In function `btSoftBodyRigidBodyCollisionConfiguration::~btSoftBodyRigidBodyCollisionConfiguration()':
btSoftBodyRigidBodyCollisionConfiguration.cpp:(.text+0x9d): undefined reference to `btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o): In function `btSoftBodyRigidBodyCollisionConfiguration::btSoftBodyRigidBodyCollisionConfiguration(btDefaultCollisionConstructionInfo const&)':
btSoftBodyRigidBodyCollisionConfiguration.cpp:(.text+0xdb): undefined reference to `btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(btDefaultCollisionConstructionInfo const&)'
btSoftBodyRigidBodyCollisionConfiguration.cpp:(.text+0x26a): undefined reference to `btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o): In function `btSoftBodyRigidBodyCollisionConfiguration::~btSoftBodyRigidBodyCollisionConfiguration()':
btSoftBodyRigidBodyCollisionConfiguration.cpp:(.text+0x92): undefined reference to `btDefaultCollisionConfiguration::~btDefaultCollisionConfiguration()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o): In function `btSoftBodyRigidBodyCollisionConfiguration::getCollisionAlgorithmCreateFunc(int, int)':
btSoftBodyRigidBodyCollisionConfiguration.cpp:(.text+0x2d3): undefined reference to `btDefaultCollisionConfiguration::getCollisionAlgorithmCreateFunc(int, int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o):(.rodata._ZTI41btSoftBodyRigidBodyCollisionConfiguration[_ZTI41btSoftBodyRigidBodyCollisionConfiguration]+0x10): undefined reference to `typeinfo for btDefaultCollisionConfiguration'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyRigidBodyCollisionConfiguration.o):(.rodata._ZTV41btSoftBodyRigidBodyCollisionConfiguration[_ZTV41btSoftBodyRigidBodyCollisionConfiguration]+0x38): undefined reference to `btDefaultCollisionConfiguration::getClosestPointsAlgorithmCreateFunc(int, int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftRigidCollisionAlgorithm.o): In function `btSoftRigidCollisionAlgorithm::btSoftRigidCollisionAlgorithm(btPersistentManifold*, btCollisionAlgorithmConstructionInfo const&, btCollisionObjectWrapper const*, btCollisionObjectWrapper const*, bool)':
btSoftRigidCollisionAlgorithm.cpp:(.text+0xc0): undefined reference to `btCollisionAlgorithm::btCollisionAlgorithm(btCollisionAlgorithmConstructionInfo const&)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::serialize(btSerializer*)':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x9ab): undefined reference to `btDiscreteDynamicsWorld::serializeDynamicsWorldInfo(btSerializer*)'
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x9d1): undefined reference to `btDiscreteDynamicsWorld::serializeRigidBodies(btSerializer*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::~btSoftMultiBodyDynamicsWorld()':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0xb26): undefined reference to `btMultiBodyDynamicsWorld::~btMultiBodyDynamicsWorld()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::btSoftMultiBodyDynamicsWorld(btDispatcher*, btBroadphaseInterface*, btMultiBodyConstraintSolver*, btCollisionConfiguration*, btSoftBodySolver*)':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0xb87): undefined reference to `btMultiBodyDynamicsWorld::btMultiBodyDynamicsWorld(btDispatcher*, btBroadphaseInterface*, btMultiBodyConstraintSolver*, btCollisionConfiguration*)'
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x1159): undefined reference to `btMultiBodyDynamicsWorld::~btMultiBodyDynamicsWorld()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::predictUnconstraintMotion(float)':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x118f): undefined reference to `btDiscreteDynamicsWorld::predictUnconstraintMotion(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::internalSingleStepSimulation(float)':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x1253): undefined reference to `btDiscreteDynamicsWorld::internalSingleStepSimulation(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::debugDrawWorld()':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x156e): undefined reference to `btDiscreteDynamicsWorld::debugDrawWorld()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::~btSoftMultiBodyDynamicsWorld()':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0xae5): undefined reference to `btMultiBodyDynamicsWorld::~btMultiBodyDynamicsWorld()'
btSoftMultiBodyDynamicsWorld.cpp:(.text+0xb0f): undefined reference to `btMultiBodyDynamicsWorld::~btMultiBodyDynamicsWorld()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btSoftMultiBodyDynamicsWorld::removeCollisionObject(btCollisionObject*)':
btSoftMultiBodyDynamicsWorld.cpp:(.text+0x14da): undefined reference to `btDiscreteDynamicsWorld::removeCollisionObject(btCollisionObject*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o): In function `btDiscreteDynamicsWorld::updateVehicles(float)':
btSoftMultiBodyDynamicsWorld.cpp:(.text._ZN23btDiscreteDynamicsWorld14updateVehiclesEf[_ZN23btDiscreteDynamicsWorld14updateVehiclesEf]+0x1): undefined reference to `btDiscreteDynamicsWorld::updateActions(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTI28btSoftMultiBodyDynamicsWorld[_ZTI28btSoftMultiBodyDynamicsWorld]+0x10): undefined reference to `typeinfo for btMultiBodyDynamicsWorld'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x58): undefined reference to `btDiscreteDynamicsWorld::addCollisionObject(btCollisionObject*, int, int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x78): undefined reference to `btDiscreteDynamicsWorld::stepSimulation(float, int, float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x80): undefined reference to `btDiscreteDynamicsWorld::addConstraint(btTypedConstraint*, bool)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x88): undefined reference to `btDiscreteDynamicsWorld::removeConstraint(btTypedConstraint*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x90): undefined reference to `btDiscreteDynamicsWorld::addAction(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x98): undefined reference to `btDiscreteDynamicsWorld::removeAction(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xa0): undefined reference to `btDiscreteDynamicsWorld::setGravity(btVector3 const&)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xa8): undefined reference to `btDiscreteDynamicsWorld::getGravity() const'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xb0): undefined reference to `btDiscreteDynamicsWorld::synchronizeMotionStates()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xb8): undefined reference to `btDiscreteDynamicsWorld::addRigidBody(btRigidBody*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xc0): undefined reference to `btDiscreteDynamicsWorld::addRigidBody(btRigidBody*, int, int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xc8): undefined reference to `btDiscreteDynamicsWorld::removeRigidBody(btRigidBody*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xd0): undefined reference to `btDiscreteDynamicsWorld::setConstraintSolver(btConstraintSolver*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xd8): undefined reference to `btDiscreteDynamicsWorld::getConstraintSolver()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xe0): undefined reference to `btDiscreteDynamicsWorld::getNumConstraints() const'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xe8): undefined reference to `btDiscreteDynamicsWorld::getConstraint(int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0xf0): undefined reference to `btDiscreteDynamicsWorld::getConstraint(int) const'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x100): undefined reference to `btMultiBodyDynamicsWorld::clearForces()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x108): undefined reference to `btDiscreteDynamicsWorld::addVehicle(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x110): undefined reference to `btDiscreteDynamicsWorld::removeVehicle(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x118): undefined reference to `btDiscreteDynamicsWorld::addCharacter(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x120): undefined reference to `btDiscreteDynamicsWorld::removeCharacter(btActionInterface*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x130): undefined reference to `btMultiBodyDynamicsWorld::integrateTransforms(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x138): undefined reference to `btMultiBodyDynamicsWorld::calculateSimulationIslands()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x140): undefined reference to `btMultiBodyDynamicsWorld::solveConstraints(btContactSolverInfo&)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x148): undefined reference to `btMultiBodyDynamicsWorld::updateActivationState(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x158): undefined reference to `btDiscreteDynamicsWorld::createPredictiveContacts(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x160): undefined reference to `btDiscreteDynamicsWorld::saveKinematicState(float)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x168): undefined reference to `btDiscreteDynamicsWorld::debugDrawConstraint(btTypedConstraint*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x170): undefined reference to `btMultiBodyDynamicsWorld::applyGravity()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x188): undefined reference to `btMultiBodyDynamicsWorld::serializeMultiBodies(btSerializer*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x190): undefined reference to `btMultiBodyDynamicsWorld::addMultiBody(btMultiBody*, int, int)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x198): undefined reference to `btMultiBodyDynamicsWorld::removeMultiBody(btMultiBody*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x1a8): undefined reference to `btMultiBodyDynamicsWorld::addMultiBodyConstraint(btMultiBodyConstraint*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x1c8): undefined reference to `btMultiBodyDynamicsWorld::removeMultiBodyConstraint(btMultiBodyConstraint*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x1d0): undefined reference to `btMultiBodyDynamicsWorld::debugDrawMultiBodyConstraint(btMultiBodyConstraint*)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x1d8): undefined reference to `btMultiBodyDynamicsWorld::clearMultiBodyConstraintForces()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftMultiBodyDynamicsWorld.o):(.rodata._ZTV28btSoftMultiBodyDynamicsWorld[_ZTV28btSoftMultiBodyDynamicsWorld]+0x1e0): undefined reference to `btMultiBodyDynamicsWorld::clearMultiBodyForces()'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftSoftCollisionAlgorithm.o): In function `btSoftSoftCollisionAlgorithm::btSoftSoftCollisionAlgorithm(btPersistentManifold*, btCollisionAlgorithmConstructionInfo const&, btCollisionObjectWrapper const*, btCollisionObjectWrapper const*)':
btSoftSoftCollisionAlgorithm.cpp:(.text+0x58): undefined reference to `btCollisionAlgorithm::btCollisionAlgorithm(btCollisionAlgorithmConstructionInfo const&)'
../../src/BulletSoftBody/libBulletSoftBody.a(btSoftBodyConcaveCollisionAlgorithm.o): In function `btSoftBodyConcaveCollisionAlgorithm::btSoftBodyConcaveCollisionAlgorithm(btCollisionAlgorithmConstructionInfo const&, btCollisionObjectWrapper const*, btCollisionObjectWrapper const*, bool)':
btSoftBodyConcaveCollisionAlgorithm.cpp:(.text+0x15a8): undefined reference to `btCollisionAlgorithm::btCollisionAlgorithm(btCollisionAlgorithmConstructionInfo const&)'
collect2: error: ld returned 1 exit status
examples/SharedMemory/CMakeFiles/App_PhysicsServer_SharedMemory.dir/build.make:1456: recipe for target 'examples/SharedMemory/App_PhysicsServer_SharedMemory' failed
make[2]: *** [examples/SharedMemory/App_PhysicsServer_SharedMemory] Error 1
CMakeFiles/Makefile2:631: recipe for target 'examples/SharedMemory/CMakeFiles/App_PhysicsServer_SharedMemory.dir/all' failed
make[1]: *** [examples/SharedMemory/CMakeFiles/App_PhysicsServer_SharedMemory.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by erwincoumans** [comment]
What if you use pip install pybullet instead (or sudo pip install pybullet or sudo pip3 install pybullet)?

**Comment by consultit** [comment]
Hi unfortunately premake at least until commit 0421c60, does not build correctly with gcc 6.3.0 (Debian 9.3) and gcc 5.4.0 (Ubuntu 16.04).
After analyzing a bit I saw that the problems are related to the linking phase:
- the plugin system does not link with the `dl` library
- the linker complains that various static libraries (ie declared `kind StaticLib`) are not compiled with the `-fPIC` flag

To solve the first problem I have included, in several premake.lua, the code:
```
if os.is ("Linux") then
     Links {"dl"}
end
```
The second I solved by inserting in all the premake.lua that define the static libraries the code:
```
     if os.is ("Linux") then
         buildoptions {"- fPIC"}
     end
```
To see the changes made, I've attached a simple `git diff master` with the latest commit 0421c60
[bullet3-premake.diff.txt](https://github.com/bulletphysics/bullet3/files/1710791/bullet3-premake.diff.txt)

Bye

**Comment by erwincoumans** [comment]
Can you try latest revision, this pull request should fix it for premake and cmake:
https://github.com/bulletphysics/bullet3/pull/1557
